// <auto-generated />
using System;
using LD4.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LD4.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241213161830_Seeding-students")]
    partial class Seedingstudents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("CourseStudent", b =>
                {
                    b.Property<int>("CoursesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CoursesId", "StudentsId");

                    b.HasIndex("StudentsId");

                    b.ToTable("CourseStudent");
                });

            modelBuilder.Entity("LD4.Domain.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndingAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("InstructorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartingAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndingAt = new DateTime(1, 1, 1, 1, 30, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = 1,
                            StartingAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Topic = "why 2 + 2 != 4"
                        },
                        new
                        {
                            Id = 2,
                            EndingAt = new DateTime(2024, 12, 13, 19, 48, 30, 621, DateTimeKind.Local).AddTicks(7969),
                            InstructorId = 1,
                            StartingAt = new DateTime(2024, 12, 13, 18, 18, 30, 621, DateTimeKind.Local).AddTicks(7932),
                            Topic = "why 2 + 2 != 4"
                        },
                        new
                        {
                            Id = 3,
                            EndingAt = new DateTime(2024, 12, 14, 20, 18, 30, 621, DateTimeKind.Local).AddTicks(7974),
                            InstructorId = 1,
                            StartingAt = new DateTime(2024, 12, 14, 18, 18, 30, 621, DateTimeKind.Local).AddTicks(7972),
                            Topic = "Introduction to Quantum Mechanics"
                        },
                        new
                        {
                            Id = 4,
                            EndingAt = new DateTime(2024, 12, 15, 19, 48, 30, 621, DateTimeKind.Local).AddTicks(7978),
                            InstructorId = 1,
                            StartingAt = new DateTime(2024, 12, 15, 18, 18, 30, 621, DateTimeKind.Local).AddTicks(7977),
                            Topic = "Advanced Mathematics"
                        },
                        new
                        {
                            Id = 5,
                            EndingAt = new DateTime(2024, 12, 16, 20, 18, 30, 621, DateTimeKind.Local).AddTicks(7982),
                            InstructorId = 2,
                            StartingAt = new DateTime(2024, 12, 16, 18, 18, 30, 621, DateTimeKind.Local).AddTicks(7980),
                            Topic = "Philosophy of Science"
                        },
                        new
                        {
                            Id = 6,
                            EndingAt = new DateTime(2024, 12, 17, 19, 48, 30, 621, DateTimeKind.Local).AddTicks(7985),
                            InstructorId = 2,
                            StartingAt = new DateTime(2024, 12, 17, 18, 18, 30, 621, DateTimeKind.Local).AddTicks(7984),
                            Topic = "History of Art"
                        });
                });

            modelBuilder.Entity("LD4.Domain.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("JoinedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            JoinedOn = new DateOnly(2001, 7, 7),
                            Name = "Instruktors 1",
                            Surname = "aaaaaaaaaaa"
                        },
                        new
                        {
                            Id = 2,
                            JoinedOn = new DateOnly(2010, 12, 1),
                            Name = "Instruktors 2",
                            Surname = "bbbbbbbbbbbbbbb"
                        });
                });

            modelBuilder.Entity("LD4.Domain.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "pirmais"
                        },
                        new
                        {
                            Id = 2,
                            Name = "otrais"
                        },
                        new
                        {
                            Id = 3,
                            Name = "tresais"
                        });
                });

            modelBuilder.Entity("CourseStudent", b =>
                {
                    b.HasOne("LD4.Domain.Course", null)
                        .WithMany()
                        .HasForeignKey("CoursesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LD4.Domain.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LD4.Domain.Course", b =>
                {
                    b.HasOne("LD4.Domain.Instructor", null)
                        .WithMany("Courses")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LD4.Domain.Instructor", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
